// Datos geográficos del Ecuador basados en la División Política Administrativa (DPA)
// del INEC. Incluye 24 provincias y 221 cantones (post-2013, con La Concordia
// reasignada a Santo Domingo de los Tsáchilas).
//
// Códigos: provincia = 2 dígitos secuenciales según orden DPA; cantón = código
// provincia + 2 dígitos correlativos según orden de creación dentro de la provincia.

export const PROVINCES: { code: string; name: string }[] = [
  { code: "01", name: "Azuay" },
  { code: "02", name: "Bolívar" },
  { code: "03", name: "Cañar" },
  { code: "04", name: "Carchi" },
  { code: "05", name: "Cotopaxi" },
  { code: "06", name: "Chimborazo" },
  { code: "07", name: "El Oro" },
  { code: "08", name: "Esmeraldas" },
  { code: "09", name: "Guayas" },
  { code: "10", name: "Imbabura" },
  { code: "11", name: "Loja" },
  { code: "12", name: "Los Ríos" },
  { code: "13", name: "Manabí" },
  { code: "14", name: "Morona Santiago" },
  { code: "15", name: "Napo" },
  { code: "16", name: "Pastaza" },
  { code: "17", name: "Pichincha" },
  { code: "18", name: "Tungurahua" },
  { code: "19", name: "Zamora Chinchipe" },
  { code: "20", name: "Galápagos" },
  { code: "21", name: "Sucumbíos" },
  { code: "22", name: "Orellana" },
  { code: "23", name: "Santo Domingo de los Tsáchilas" },
  { code: "24", name: "Santa Elena" },
];

export const CANTONS_BY_PROVINCE: Record<string, string[]> = {
  "01": [
    "Cuenca",
    "Girón",
    "Gualaceo",
    "Nabón",
    "Paute",
    "Pucará",
    "San Fernando",
    "Santa Isabel",
    "Sigsig",
    "Oña",
    "Chordeleg",
    "El Pan",
    "Sevilla de Oro",
    "Guachapala",
    "Camilo Ponce Enríquez",
  ],
  "02": [
    "Guaranda",
    "Chillanes",
    "Chimbo",
    "Echeandía",
    "San Miguel",
    "Caluma",
    "Las Naves",
  ],
  "03": [
    "Azogues",
    "Biblián",
    "Cañar",
    "La Troncal",
    "El Tambo",
    "Déleg",
    "Suscal",
  ],
  "04": [
    "Tulcán",
    "Bolívar",
    "Espejo",
    "Mira",
    "Montúfar",
    "San Pedro de Huaca",
  ],
  "05": [
    "Latacunga",
    "La Maná",
    "Pangua",
    "Pujilí",
    "Salcedo",
    "Saquisilí",
    "Sigchos",
  ],
  "06": [
    "Riobamba",
    "Alausí",
    "Colta",
    "Chambo",
    "Chunchi",
    "Guamote",
    "Guano",
    "Pallatanga",
    "Penipe",
    "Cumandá",
  ],
  "07": [
    "Machala",
    "Arenillas",
    "Atahualpa",
    "Balsas",
    "Chilla",
    "El Guabo",
    "Huaquillas",
    "Marcabelí",
    "Pasaje",
    "Piñas",
    "Portovelo",
    "Santa Rosa",
    "Zaruma",
    "Las Lajas",
  ],
  "08": [
    "Esmeraldas",
    "Eloy Alfaro",
    "Muisne",
    "Quinindé",
    "San Lorenzo",
    "Atacames",
    "Rioverde",
  ],
  "09": [
    "Guayaquil",
    "Alfredo Baquerizo Moreno (Jujan)",
    "Balao",
    "Balzar",
    "Colimes",
    "Daule",
    "Durán",
    "El Empalme",
    "El Triunfo",
    "Milagro",
    "Naranjal",
    "Naranjito",
    "Palestina",
    "Pedro Carbo",
    "Samborondón",
    "Santa Lucía",
    "Salitre (Urbina Jado)",
    "San Jacinto de Yaguachi",
    "Playas (General Villamil)",
    "Simón Bolívar",
    "Coronel Marcelino Maridueña",
    "Lomas de Sargentillo",
    "Nobol",
    "General Antonio Elizalde (Bucay)",
    "Isidro Ayora",
  ],
  "10": [
    "Ibarra",
    "Antonio Ante",
    "Cotacachi",
    "Otavalo",
    "Pimampiro",
    "San Miguel de Urcuquí",
  ],
  "11": [
    "Loja",
    "Calvas",
    "Catamayo",
    "Celica",
    "Chaguarpamba",
    "Espíndola",
    "Gonzanamá",
    "Macará",
    "Paltas",
    "Puyango",
    "Saraguro",
    "Sozoranga",
    "Zapotillo",
    "Pindal",
    "Quilanga",
    "Olmedo",
  ],
  "12": [
    "Babahoyo",
    "Baba",
    "Montalvo",
    "Puebloviejo",
    "Quevedo",
    "Urdaneta",
    "Ventanas",
    "Vínces",
    "Palenque",
    "Buena Fe",
    "Valencia",
    "Mocache",
    "Quinsaloma",
  ],
  "13": [
    "Portoviejo",
    "Bolívar",
    "Chone",
    "El Carmen",
    "Flavio Alfaro",
    "Jipijapa",
    "Junín",
    "Manta",
    "Montecristi",
    "Paján",
    "Pichincha",
    "Rocafuerte",
    "Santa Ana",
    "Sucre",
    "Tosagua",
    "24 de Mayo",
    "Pedernales",
    "Olmedo",
    "Puerto López",
    "Jama",
    "Jaramijó",
    "San Vicente",
  ],
  "14": [
    "Morona",
    "Gualaquiza",
    "Limón Indanza",
    "Palora",
    "Santiago",
    "Sucúa",
    "Huamboya",
    "San Juan Bosco",
    "Taisha",
    "Logroño",
    "Pablo Sexto",
    "Tiwintza",
  ],
  "15": [
    "Tena",
    "Archidona",
    "El Chaco",
    "Quijos",
    "Carlos Julio Arosemena Tola",
  ],
  "16": ["Pastaza", "Mera", "Santa Clara", "Arajuno"],
  "17": [
    "Quito",
    "Cayambe",
    "Mejía",
    "Pedro Moncayo",
    "Rumiñahui",
    "San Miguel de Los Bancos",
    "Pedro Vicente Maldonado",
    "Puerto Quito",
  ],
  "18": [
    "Ambato",
    "Baños de Agua Santa",
    "Cevallos",
    "Mocha",
    "Patate",
    "Quero",
    "San Pedro de Pelileo",
    "Santiago de Píllaro",
    "Tisaleo",
  ],
  "19": [
    "Zamora",
    "Chinchipe",
    "Nangaritza",
    "Yacuambi",
    "Yantzaza",
    "El Pangui",
    "Centinela del Cóndor",
    "Palanda",
    "Paquisha",
  ],
  "20": ["San Cristóbal", "Isabela", "Santa Cruz"],
  "21": [
    "Lago Agrio",
    "Gonzalo Pizarro",
    "Putumayo",
    "Shushufindi",
    "Sucumbíos",
    "Cascales",
    "Cuyabeno",
  ],
  "22": ["Orellana", "Aguarico", "La Joya de los Sachas", "Loreto"],
  "23": ["Santo Domingo", "La Concordia"],
  "24": ["Santa Elena", "La Libertad", "Salinas"],
};

export type CantonRow = {
  province_code: string;
  code: string;
  name: string;
};

export function buildCantonRows(): CantonRow[] {
  const rows: CantonRow[] = [];
  for (const province of PROVINCES) {
    const cantons = CANTONS_BY_PROVINCE[province.code] ?? [];
    cantons.forEach((name, index) => {
      const code = `${province.code}${String(index + 1).padStart(2, "0")}`;
      rows.push({ province_code: province.code, code, name });
    });
  }
  return rows;
}
